categories = [
    {
        "path": "/doc/generate-answer",
        "tools": [
            "ad-campaign",
            "big-ideas",
            "blog-topics",
            "campaign-theme",
            "contest-ideas",
            "creative-freestyle",
            "creative-insights",
            "crisis-response",
            "event-ideas",
            "guerilla-marketing",
            "influencer-marketing",
            "invento",
            "mobile-marketing",
            "newsletter-topics",
            "podcast-episodes",
            "problem-solver",
            "promotion-idea",
            "publicity-stunt",
            "video-treatment",
            "viral-ideas",
            "advanced-idea-generator",
            "strategy-thinking",
        ],
    },
    {
        "path": "/doc/generate-headline",
        "tools": [
            "article-headline",
            "email-subject",
            "product-name",
            "book-title",
            "website-hero-title",
            "general-headline",
            "google-ad-headline",
            "facebook-ads-headline",
            "linkedin-profile-headline",
            "pinterest-headline",
            "seo-meta-description",
            "youtube-title",
            "headline-only",
        ],
    },
    {
        "path": "/doc/generate-message",
        "tools": [
            "key-messages",
            "talking-points",
            "positioning-statement",
            "brand-story",
            "marketing-angle",
            "value-proposition",
            "elevator-pitch",
            "news-hook",
            "profile-summary",
            "freestyle-writer",
            "editorial-strategy",
            "story-brand",
        ],
    },
    {
        "path": "/doc/generate-social-media",
        "tools": [
            "ig-caption",
            "product-launch",
            "youtube-description",
            "quora-answers",
            "viral-post-hook",
            "social-post",
            "linkedin-post",
            "linkedin-outreach",
            "twitter-thread",
            "twitter-post",
        ],
    },
    {
        "path": "/doc/generate-promote",
        "tools": [
            "headline-slogan",
            "tagline-writer",
            "video-script",
            "general-copy",
            "aida",
            "pas",
            "bab",
            "fab",
            "google-ads",
            "facebook-ads",
            "amazon-ads",
            "billboard-copy",
            "print-ad",
            "radio-ad",
            "magazine-ad",
            "copy-freestyle",
            "advertising-idea",
            "linkedin-ad",
            "micro-copy",
        ],
    },
    {
        "path": "/doc-v2/generate-article",
        "tools": ["article-writer"],
    },
    {
        "path": "/doc/generate-media-pitch",
        "tools": ["Media Pitch"],
    },
    {
        "path": "/doc/generate-question",
        "tools": ["Interview", "Research", "Survey"],
    },
    {
        "path": "/doc/generate-quote",
        "tools": ["Quote"],
    },
    {
        "path": "/doc/generate-summary",
        "tools": [
            "proposal-intro",
            "proposal-summary",
            "simplify",
            "speech-intro",
            "blog-intro",
            "blog-outline",
            "essay-intro",
            "essay-outline",
            "conclusion",
            "freestyle",
            "reframer",
            "bullet-point",
            "rewriter",
            "analogy",
            "abstract-writer",
            "course-outline",
        ],
    },
    {
        "path": "/doc/generate-correspondence",
        "tools": [
            "perfect-email",
            "memo",
            "letter",
            "media-statement",
            "press-release",
            "apology",
            "call-script",
            "question-answering",
            "email-sequence",
            "influencer-outreach",
        ],
    },
    {
        "path": "/doc/generate-entertainment",
        "tools": [
            "logline",
            "blurb",
            "plot-summary",
            "character-sketch",
            "story-teller",
            "creative-rationale",
            "screen-play",
            "vignette",
            "song-writing",
            "first-page",
            "prompt-crafter",
            "creative-outline",
            "prompt-template",
            "comedy-sketch-scenarios",
        ],
    },
]
